name: Deploy
on:
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: |
          echo Running tests!

  staging:
    name: Staging
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create image tag
        id: image
        run: |
          sha=$(git rev-parse --short HEAD)
          ts=$(date -u +%Y-%m-%dT%H-%M-%S%Z)
          echo "::set-output name=tag::${sha}-${ts}"
      - name: Build & push
        run: |
          echo docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t REGISTRY/REPOSITORY:stg-${{ steps.image.outputs.tag }} .
          echo docker push REGISTRY/REPOSITORY:${{ steps.image.outputs.tag }}
    outputs:
      tag: ${{ steps.image.outputs.tag }}

  production:
    name: Production
    needs: [staging]
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull & push
        run: |
          echo docker pull REGISTRY/REPOSITORY:stg-${{ needs.staging.outputs.tag }}
          echo docker tag REGISTRY/REPOSITORY:stg-${{ needs.staging.outputs.tag }} REGISTRY/REPOSITORY:prd-${{ needs.staging.outputs.tag }}
          echo docker push REGISTRY/REPOSITORY:prd-${{ needs.staging.outputs.tag }}