name: Deploy

on:
  push:
    branches: [main]

jobs:
  preparation:
    name: preparation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: preparer
        id: preparer
        run: |
          sha=$(git rev-parse --short HEAD)
          ts=$(date +%s)
          echo "::set-output name=tag::${sha}-${ts}"
    outputs:
      tag: ${{ steps.preparer.outputs.tag }}

  # unit tests??

  build:
    name: build
    needs: [preparation]
    runs-on: ubuntu-latest
    steps:
      - name: builder
        run: echo Hello build ${{ needs.preparation.outputs.tag }}!

  staging:
    name: staging
    needs: [preparation, build]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo I am deploying to staging ${{ needs.preparation.outputs.tag }}!

  # integration tests??

  production:
    name: deploy to production
    needs: [preparation, staging]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo I am deploying to production ${{ needs.preparation.outputs.tag }}!